version: "3.8"

services:
  app:
    container_name: app-run
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8080:8080"

  database:
    container_name: TablicDOC
    image: postgres
    environment:
      POSTGRES_PASSWORD: elma
    ports:
      - "5432:5435"

